provisionDataStore:
  cassandra: false
  elasticsearch: false

storage:
  type: elasticsearch
  elasticsearch:
    scheme: http
    host: elasticsearch-master
    port: 9200
    user: elastic
    usePassword: false

agent:   
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 25m #default 256m
      memory: 128Mi

collector:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 50m #default 500m
      memory: 512Mi

query:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests: 
       cpu: 10m #default 256m
       memory: 128Mi

esIndexCleaner:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 10m #default 256m
      memory: 128Mi

esRollover:
  enabled: true
  extraEnv:
    - name: CONDITIONS
      value: '{
        "max_age": "30d",
        "max_size": "30GB" 
      }'
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 10m #default 256m
      memory: 128Mi

esLookback:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 10m #default 256m
      memory: 128Mi

# Only for testing
hotrod:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi

# Total
#   limits:
#     cpu: 220m
#     memory: 626Mi
#   requests:
#     cpu: 800m
#     memory: 596Mi