name: CI for Merge on dev

on:
  push:
    tags:
      - v*
    branches: [ dev, hotfix/workflows-update ]

env:
  DEV_GKE_USER: ${{ secrets.SERVICEACCOUNT_EMAIL }}
  DEV_GKE_JSON: ${{ secrets.SERVICEACCOUNT_JSONKEY }}

jobs:
  deploy-tooling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup helm/kubectl env
      run: |
        sudo echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        sudo apt-get install apt-transport-https ca-certificates gnupg -y
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update
        sudo apt-get install google-cloud-sdk -y
        sudo apt-get install kubectl -y
        printf '${{ env.DEV_GKE_JSON }}' > ubivius-deployments-5e62532eb5a9.json
        gcloud auth activate-service-account ${{ env.DEV_GKE_USER }} --key-file=ubivius-deployments-5e62532eb5a9.json
        gcloud container clusters get-credentials test-environment --zone us-east1-c --project ubivius-deployments
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm repo add elastic https://helm.elastic.co
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
        helm repo update
    - name: Push with valuefile
      run: |
        IN=$(echo ${GITHUB_REPOSITORY})
        NAME=${IN#"Ubivius/telemetry-"}
        chmod 700 .github/helm_update.sh
        ./.github/helm_update.sh $NAME
